services:
  marimo-notebook-docker:
    build:
      args:
        NOTEBOOK_NAME: docker
      context: .
      dockerfile: Dockerfile
    container_name: marimo-container-docker
    image: marimo-notebook-docker
    ports:
    - 8080:8080
  marimo-notebook-marimo:
    build:
      args:
        NOTEBOOK_NAME: marimo
      context: .
      dockerfile: Dockerfile
    container_name: marimo-container-marimo
    image: marimo-notebook-marimo
    ports:
    - 8081:8080
  marimo-notebook-postgres:
    build:
      args:
        NOTEBOOK_NAME: postgres
      context: .
      dockerfile: Dockerfile
    container_name: marimo-container-postgres
    image: marimo-notebook-postgres
    ports:
    - 8082:8080
